[global]
seed = "random"  # -s <str>
quiet = false    # -q
output = false   # -o <filename>

[glyphs]
font_name = "fonts/Metafont.ttf"  # -fn <str>
font_size = 10                    # -fs <int>
font_margin = 2                   # -fm <int>
font_aliasing = true              # -fa

glyph_set = ":borders"       # -g  <glyphset | str>
glyph_color_set = ":casual"  # -gc <colorset> | <color> [<color> ...]
background_color = ":black"  # -bg <color>

image_width = 156       # -w <int>
image_height = 156      # -h <int>
image_scale_factor = 4  # -x <int>
