[help]
# Show help message
# -help --help

# Show available aliases (stored in groups.py)
# 
# Glyphs
# --show-glyphsets
# 
# Colors
# --show-colors
# --show-colorsets
# 
# Zombatar colors
# --show-bright-colors
# --show-common-colors
# --show-skin-colors

[global]
seed = ':random'   # -s --seed <str>
show_seed = false  # -ss --show-seed

quiet = false    # -q
output = false   # -o <filename>

[glyphs]
font_name = 'fonts/Metafont.ttf'  # -fn <str>
font_size = 10                    # -fs <int>
font_padding = 2                  # -fp -fm <int>
font_aliasing = true              # -fa

glyphset = ':borders'          # -g  <glyphset | str>
colorset = ':casual'           # -c <colorset> | <color> [<color> ...]
background_color = ':c:black'  # -bg <color: r,g,b | #rrggbb | #rgb>

image_width = 10   # -w <int>
image_height = 10  # -h <int>
as = 'tiles'       # -as {'pixels', 'tiles'}

image_scale_factor = 4  # -x <int>

[enemies]
face = ':random'      # -f <int: 1-31>
level = ':random'     # -l <int: 1-99>
hp = ':random'        # -hp <int: 0-999>
max_hp = ':random'    # -mhp <int: 1-999>
mana = ':random'      # -m <int: 0-999>
max_mana = ':random'  # -mm <int: 1-999>
effects = ':random'   # -e <str: 1-6 | 0>

image_scale_factor = 8  # -x <int>

[zombatars]
background = ':random'        # -bg <int: 1-5>
background_color = ':random'  # -bgc <int: 1-18 | bright_color>
skin_color = ':random'        # -sc <int: 1-12 | skin_color>
cloth = ':random'             # -c <int: 0-12>
tidbit = ':random'            # -t <int: 0-14>
tidbit_color = ':random'      # -tc <int: 1-18 | bright_color>
accessory = ':random'         # -a <int: 0-16>
accessory_color = ':random'   # -ac <int: 1-18 | bright_color>
mustache = ':random'          # -m <int: 0-24>
mustache_color = ':random'    # -mc <int: 1-18 | common_color>
hair = ':random'              # -h <int: 0-16>
hair_color = ':random'        # -hc <int: 1-18 | common_color>
eyewear = ':random'           # -e <int: 0-16>
eyewear_color = ':random'     # -ec <int: 1-18 | bright_color>
hat = ':random'               # -hat <int: 0-14>
hat_color = ':random'         # -hatc <int: 1-18 | bright_color>

image_scale_factor = 4  # -x <int>

[mapper]
show_tiles = false  # -d --show-tiles

tileset = ':cross'  # -t <tileset | path>
tile_limit = false  # -l -tl -lim <int>
tile_padding = 1    # -p -tp <int>

colorset = ':casual'           # -c -tc <colorset> | <color> [<color> ...]
background_color = ':c:black'  # -bg <color: r,g,b | #rrggbb | #rgb>
color_style = ':spot'          # -m -cs {':random', ':pulse', ':spot'}

image_width = 26   # -w <int>
image_height = 26  # -h <int>
as = 'tiles'       # -as {'pixels', 'tiles'}

image_scale_factor = 4  # -x <int>

[worm]
move_straight = true    # -ms
move_diagonal = false   # -md
move_backwards = false  # -mb

step_min_length = 2  # -smin <int>
step_max_length = 2  # -smax <int>
step_limit = 8169    # -l -sl -lim <int>

colorset = ':casual'           # -c <colorset> | <color> [<color> ...]
background_color = ':c:black'  # -bg <color: r,g,b | #rrggbb | #rgb>

image_width = 128   # -w <int>
image_height = 128  # -h <int>

image_scale_factor = 4  # -x <int>

[coprimes]
line_width = 3   # -lw <ing>
line_length = 3  # -l -ll <ing>

line_color = ':c:black'           # -c -lc <color: r,g,b | #rrggbb | #rgb>
background_color_a = ':c:yellow'  # -bga <color: r,g,b | #rrggbb | #rgb>
background_color_b = ':c:purple'  # -bgb <color: r,g,b | #rrggbb | #rgb>

exclude = []  # -e <figure: {:circle, :cross}>

image_width = ':random'   # -w <int>
image_height = ':random'  # -h <int>

image_scale_factor = 12  # -x <int>
